### ISSUE TITLE
Move to TS404/AlignStat?

### ISSUE THREAD

**Issue by TS404** [iracooke/AlignStatShiny#4]
Is it possible to move this code over to the TS404/AlignStat repo?

**Comment by iracooke** [comment]
I think there are some advantages to keeping them separate.

AlignStat is a package so it it needs to adhere to a strict structure and indeed it should not contain files that aren't part of the package.  Keeping it clean allows people to install directly from github and means we don't need to do anything extra when building/submitting the package to CRAN.

If we try to add the web tool into it I fear that we would just create problems for ourselves.

**Comment by TS404** [comment]
Ah yes, I see what you mean. Makes sense to keep them separate.
